from typing import TypedDict, Dict, List, Any


class Temp12k_TS_sample(TypedDict):
    mode: str
    time_id: float
    archive_type: str
    createdBy: str
    dataSetName: str
    lipdverseLink: str
    maxYear: int
    minYear: int
    originalDataURL: List[str]
    nUniqueAges: int
    originalDataUrl: str
    nUniqueOtherAges: int
    otherAgesPerKyr: str
    agesPerKyr: float
    hasDepth: int
    nUniqueGoodAges: int
    pub1_author: str
    pub1_doi: str
    pub1_issue: str
    pub1_journal: str
    pub1_page: str
    pub1_pubDataUrl: str
    pub1_publisher: str
    pub1_title: str
    pub1_type: str
    pub1_volume: str
    pub1_year: int
    pub1_citeKey: str
    pub1_pages: str
    pub2_author: str
    pub2_doi: str
    pub2_issue: str
    pub2_journal: str
    pub2_page: str
    pub2_pubDataUrl: str
    pub2_publisher: str
    pub2_title: str
    pub2_type: str
    pub2_volume: str
    pub2_year: int
    pub3_author: str
    pub3_doi: str
    pub3_issue: str
    pub3_journal: str
    pub3_page: str
    pub3_pubDataUrl: str
    pub3_publisher: str
    pub3_title: str
    pub3_type: str
    pub3_volume: str
    pub3_year: int
    pub4_author: str
    pub4_doi: str
    pub4_issue: str
    pub4_journal: str
    pub4_page: str
    pub4_pubDataUrl: str
    pub4_publisher: str
    pub4_title: str
    pub4_type: str
    pub4_volume: str
    pub4_year: int
    geo_meanLon: float
    geo_meanLat: float
    geo_meanElev: float
    geo_notes: str
    geo_siteName: str
    geo_countryOcean: str
    geo_gcmdLocation: str
    context: str
    lipdVersion: float
    tableType: str
    paleoData_tableName: str
    paleoData_missingValue: str
    paleoData_filename: str
    depth: List[float]
    depthUnits: str
    age: List[float]
    ageUnits: str
    paleoData_TSid: str
    paleoData_hasMaxValue: float
    paleoData_hasMeanValue: float
    paleoData_hasMedianValue: float
    paleoData_hasMinValue: float
    paleoData_units: str
    paleoData_variableName: str
    paleoData_temperature12kUncertainty: str
    paleoData_hasResolution_hasMinValue: float
    paleoData_hasResolution_hasMaxValue: float
    paleoData_hasResolution_hasMeanValue: float
    paleoData_hasResolution_hasMedianValue: float
    paleoData_number: int
    paleoData_values: List[float]


class Temp12k_data(TypedDict):
    TS: List[Temp12k_TS_sample]
    D: Dict[str, Any]
